export const PLACEMENTS = [
  'JNT CARGO CIREBON',
  'MONDE',
  'JNT SEMARANG',
  'JNT TEGAL',
  'JNT PATI',
  'JNT EXPRESS MEDAN',
  'JNT SMQ 05',
  'JNT SMQ 99',
  'OB HQ',
  'SPRINTER JET JKT',
  'GO TO BALI',
  'CARGO BKI',
  'JNT CARGO SURABAYA',
  'JNT CARGO LAMPUNG',
  'JNT EXPRESS PEKANBARU',
  'JNT CARGO PKU',
  'JNT JKM CARGO CAKUNG',
  'JNT CARGO KOSAMBI',
  'JNT PALANGKARAYA',
  'MEDQUEST',
  'PT BIYAN BEKASI',
  'SUKABUMI',
  'SUBANG',
  'BANDUNG 99A',
  'BDO 3D',
  'BDO 5J',
  'MINISO',
  'SOG 99',
  'INDRAMAYU',
] as const;

export const EMPLOYMENT_STATUSES = ['Freelance', 'Kontrak', 'Reguler'] as const;
export const POSITIONS = ['Admin', 'Kordinator', 'Sorter', 'Driver', 'Kurir'] as const;
export const OWNERSHIP_STATUSES = ['PRIBADI', 'ORANG LAIN'] as const;
