export const PLACEMENTS = [
  'JNT CARGO CIREBON',
  'MONDE',
  'JNT SEMARANG',
  'JNT TEGAL',
  'JNT PATI',
  'JNT EXPRESS MEDAN',
  'JNT SMQ 05',
  'JNT SMQ 99',
  'OB HQ',
  'SPRINTER JET JKT',
  'GO TO BALI',
  'CARGO BKI',
  'CARGO LAMONGAN',
  'JNT CARGO SURABAYA',
  'JNT CARGO LAMPUNG',
  'JNT EXPRESS LAMPUNG',
  'JNT EXPRESS PEKANBARU',
  'JNT CARGO PKU',
  'JNT JKM CARGO CAKUNG',
  'JNT CARGO KOSAMBI',
  'JNT PALANGKARAYA',
  'MEDQUEST',
  'PT BIYAN BEKASI',
  'LAZADA',
] as const;

export const EMPLOYMENT_STATUSES = ['Freelance', 'Kontrak', 'Reguler'] as const;
export const POSITIONS = ['Admin', 'Kordinator', 'Sorter', 'Driver', 'Kurir'] as const;
export const LAZADA_POSITIONS = ['KURIR', 'Harian Lepas (HL)'] as const;
export const LAZADA_HUBS = [
  'DKI Jakarta / Kota Jakarta Barat',
  'DKI Jakarta / Kota Jakarta Pusat',
  'DKI Jakarta / Kota Jakarta Selatan',
  'DKI Jakarta / Kota Jakarta Timur',
  'DKI Jakarta / Kota Jakarta Utara',
  'Kab. Badung',
  'Kab. Bandung Barat',
  'Kab. Bantul',
  'Kab. Banyumas',
  'Kab. Batang',
  'Kab. Bekasi',
  'Kab. Bogor',
  'Kab. Cianjur',
  'Kab. Cilacap',
  'Kab. Cirebon',
  'Kab. Deli Serdang',
  'Kab. Garut',
  'Kab. Grobogan',
  'Kab. Karanganyar',
  'Kab. Karawang',
  'Kab. Klaten',
  'Kab. Ogan Ilir',
  'Kab. Pasuruan',
  'Kab. Pati',
  'Kab. Purwakarta',
  'Kab. Semarang',
  'Kab. Serang',
  'Kab. Sidoarjo',
  'Kab. Sukoharjo',
  'Kab. Tangerang',
  'Kab. Wonogiri',
  'Kota Balikpapan',
  'Kota Bandar Lampung',
  'Kota Bandung',
  'Kota Bekasi',
  'Kota Bogor',
  'Kota Cimahi',
  'Kota Denpasar',
  'Kota Depok',
  'Kota Makassar',
  'Kota Malang',
  'Kota Medan',
  'Kota Padang',
  'Kota Palembang',
  'Kota Pekanbaru',
  'Kota Semarang',
  'Kota Serang',
  'Kota Surabaya',
  'Kota Tangerang',
  'Kota Tangerang Selatan',
] as const;
export const OWNERSHIP_STATUSES = ['PRIBADI', 'ORANG LAIN'] as const;
